### ISSUE TITLE
Mutagen does not work correct

### ISSUE THREAD

**Issue by nik4152** [mutagen-io/docker-desktop-extension-issues#5]
Sorry but I disappointment

Why mutagen not set permissions 777
`          defaultFileMode: 0777`
`          defaultDirectoryMode: 0777`
 i tried 0755 0644 (maybe set permit only for folder "var 777?),
how disable override permit or set correct 
<img width="460" alt="Знімок екрана 2022-12-17 о 14 22 32" src="https://user-images.githubusercontent.com/1374095/208241651-32e05bb4-6cec-482d-944d-ba265e8be25b.png">
<img width="714" alt="Знімок екрана 2022-12-17 о 14 22 24" src="https://user-images.githubusercontent.com/1374095/208241657-56d6961f-3fce-45d3-a08a-8a8bd98150a5.png">
, mutagen desktop same does not work  or how connected in mutagen-compose?

a paid program that does not work, maybe it's just me, I don't know, but the disappointment does not decrease

**Comment by xenoscopic** [comment]
@nik4152 I'm sorry that you're disappointed, but I think you may be misunderstanding the purpose of the extension.

The Docker Desktop extension is **_unrelated_** to Mutagen Compose.  You do not need the extension to use Mutagen Compose.

The Docker Desktop extension is designed as a replacement/alternative to Mutagen Compose.  It is designed for users who have a simple Compose configuration or who can't use Mutagen Compose.  The extension allows them to continue using Docker Compose with their existing projects without making any changes.  The extension is designed to emulate the observable behavior of gRPC FUSE and Virtiofs, but with better performance, which is why it sets permissions with a fixed set of values, because that's what gRPC FUSE and Virtiofs do as well.

Mutagen Compose is an alternative to the extension.  Mutagen Compose does not require the extension and shouldn't be used with the extension.  In your case, you would want to use Mutagen Compose to target either the Docker Desktop Docker engine or a remote Docker engine.  If you're having trouble getting Mutagen Compose to work, please drop into the [Mutagen Community Slack Workspace](https://mutagen.io/slack).

If you've already purchased a subscription to the extension, you can cancel your subscription and you'll receive a pro-rated refund.
